
apiVersion: v1
kind: Service
metadata:
  name: web-server-app-service
spec:
  selector:
    app: web-server-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110